### ISSUE TITLE
zenith() and ramp() need calculations checking and tidying.

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#108]
The workings of zenith() and ramp() are very flaky. I'm not entirely sure of the calculation that _should_ be going on - @rs028 are you able to point me to a standard work, or other place, where this calculation is defined?

Issues I've spotted:

- [ ] What is ramp() calculating? It seems to output max{0,x} - is that what's required?
- [ ] zenith() has an input argument theta which is calculated but never used.
- [ ] The secx calculation seems like a fudge, adding 1e-30 to avoid a division by zero - what is the real calculation supposed to be?

Related to #14 ?

**Comment by rs028** [comment]
@spco I am not 100% sure, but I think ramp() is basically a way to deal with negative numbers.  Like the usage of 1e-30 (which may appear in other parts of the code) I think these are leftovers from the model written for the FACSIMILE solver.

zenith() is related to #14. I will look into that.

**Comment by rs028** [comment]
This can be closed. The remaining issues are related to issue #14 and are being addressed in PR 198.

**Comment by spco** [comment]
Ok. I may open another issue to look at the 1e-30 issue (because it would be great if we handle the case of 0 properly, rather than fudging it), although that also comes under the JFac umbrella as well.
