### ISSUE TITLE
Inadvertent side-effect of calling jfy()

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#109]
Calling jfy() (by setting jacobian output step size to a useful size) changes the output of cosx and lha in photoRateCalcParameters.output. I think this is probably an undesired consequence, as they are calculated in zenith() (called by getEnvVarsAtT()) and should probably be only dependent on the time and lat/long?

zenith() (the source of lha and cosx) is also called by resid() (via getEnvVarsAtT()). Outputting after each call shows that these values vary within a single timestep before converging. Is this that they are changing in some nonlinear way, or is it that the time being calculated changes within the iteration, so we should expect these to also vary?

Either way, it's wrong that calling jfy() should change their values.

**Comment by spco** [comment]
Found while working on #107

**Comment by spco** [comment]
@rs028 - I'd value your thoughts on this one. 

The situation is the following: in the main loop of the AtChem program, we have `call outputPhotoRateCalcParameters( t )`, and then `call CVODE()`, and then lots of other outputs of various things like the rates and the environment variables, as well as the jacobian if required.

`FCVODE()` calls a number of functions, in particular the `FCVFUN()` function, repeatedly. This is the _inner_ loop - CVODE automatically chops the time interval between `t` and `tout` as it pleases, and integrates over those small timesteps, and then stops when it reaches `tout`. At each of those inner timesteps, it evaluates `FCVFUN()`, which includes things like calculating the zenith values, `cosx`, `dec` etc, as well as the environment variables. This means that, by the time `FCVODE()` has finished handling the _outer_ timestep (e.g. 900 seconds, as defined in `model.parameters`), it will have evaluated all these values at a time close to 900s into the timestep. Thus, when we then get to outputting the environment variables in `outputEnvVar( t )`, the environment variables are filled with values from near the end of the timestep. But we then output these to a line in a file that contains `t` as the time, which is the _beginning_ of the outer timestep.

What this all means is that what we're outputting to file normally isn't valid at the time that the line is labelled with. This is what causes the current change in the values of `cosx` and `lha` when we call `jfy( t )` - it recalculates the values back at the beginning of the timestep, rather than towards the end of the timestep. It does however mean that the values are valid for the time stamp they're given.

What should we do about this? I think the best thing is to output things at the correct time, rather than later in the timestep. I think this would just require looking at what parts are output at which stage, and order them before or after the call to `FCVODE()` as appropriate. Does that make sense and sound like a sensible approach?

**Comment by rs028** [comment]
If I understand correctly, this means that the output value and the output time are out of sync. Is that right?
I agree that should not happen. The output should have the correct timestamp. Does it answer your question?

**Comment by spco** [comment]
Yes, some of the output values are out of sync. I'll look into which need to move, and see whether rearranging the outputs is a viable option.

**Comment by spco** [comment]
Closed by #107

**Comment by spco** [comment]
For future reference, it wasn't as bad as I originally thought - moving `jfy()` to before the call to `FCVODE()` was sufficient. The other output functions correctly handle their output timings.

**Comment by rs028** [comment]
Very good! It is great to see the number of issues below 10! :)
:1st_place_medal:
