### ISSUE TITLE
make clean

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#11]
Currently __genmod* files are not removed

**Comment by spco** [comment]
I think this has been fixed since commit 421f5f10, because the __genmod* files are never built. Can you check whether this is true for you? The make clean doesn't explicitly delete them as they shouldn't be there after building anyway.

**Comment by rs028** [comment]
Okay, that's fine. I added the points in my todo list to the list of issues. you may already have addressed some of those, if so, feel free to close the issue.
