### ISSUE TITLE
constrainedFixedSpecies

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#115]
What is the purpose of constrainedFixedSpecies.config?
If a species is kept constant, then it requires only a value (eg, should have the same format of initialConcentrations.config) not a whole file like when it is constrained.

**Comment by spco** [comment]
This is exactly right - constrained species are split into "fixed-concentration constrained species" and "variable-concentration constrained species". The former are listed in `constrainedFixedSpecies.config`, in the form `name, value`, while the latter each have a file in `speciesConstraints/` directory, of the form
```
number_of_lines
time1     value1
time2    value2
...
```
See `spec_yes_plus_fixed_env_no` test for such a setup.

**Comment by spco** [comment]
#163 changes this so that the variable constrained species files just contain 
```
time1 value1
time2 value2
```
i.e. they don't have a `number_of_lines` field at the top - reduces the risk of inconsistent values.

**Comment by spco** [comment]
I think this issue is completed - @rs028 could you close this if you agree?

**Comment by rs028** [comment]
:+1:
