### ISSUE TITLE
maxNumberOfDataPoints is hard coded

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#12]
maxNumberOfDataPoints (in inputFunctions.f) should be read from modelConfiguration/model.parameters where it is set, or (better) automatically determined when the constraint files are read in

**Comment by spco** [comment]
#97 removed the hardcoded setting of this value. I'm leaving this open as I'm not certain whether the remaining calculation is correct.

**Comment by spco** [comment]
I'm happy this can be closed.
