### ISSUE TITLE
check M calculation

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#133]
Need to verify the output  of subroutine calcM (related to #23)

**Comment by spco** [comment]
Can I assign this to you? It would be helpful if you link to the source of the calculation (a paper etc) when you get round to it.

**Comment by rs028** [comment]
Yes. I will put in a PR for both #133 and #23

**Comment by rs028** [comment]
This subroutine is correct. I will just clean up and comment the code.

![m](https://cloud.githubusercontent.com/assets/7703778/25801973/1cd05ae0-33e8-11e7-8419-8ce1efc8b499.png)

**Comment by rs028** [comment]
Make sure that input of M and Pressure are consistent - related to #23

**Comment by rs028** [comment]
@spco Good stuff! :+1:
