### ISSUE TITLE
HPC submission script

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#15]
the log file from the submission script should go in the modelOutput folder together with all the other output and log files

the name of the file is currently determined by the cluster number it is submitted to; can it be changed to something more sensible?

**Comment by spco** [comment]
@rs028, could you copy your submission script into a comment here? I can then create a working copy and add that as a file in the repo. Best not to add the incorrect version as a file in its own right, as we prefer to have working code only!

**Comment by rs028** [comment]
@spco see below. Is this likely to be system dependent? If so maybe it should go in a "extra tools" directory or something? That could also be a place for the mcm_subset.fac that is currently in the main folder? just an idea.



#========================================
# job submission script for AtChem
#========================================

#PBS -joe atchem.log
#PBS -N base_v1
#PBS -l walltime=15:00:00
#PBS -l vmem=10GB
#PBS -m bea
#PBS -M rs445@le.ac.uk
#PBS -l nodes=1:ppn=1

#========================================
# code to run
#========================================
cd ~/MCM/icoza/base_v1/
./atchem

**Comment by spco** [comment]
[AtChem_script.txt](https://github.com/AtChem/AtChem/files/1088865/AtChem_script.txt)

@rs028 I think this script should work for you - could you try it out? It currently uses two output files, one for standard output and one for standard error, but if this works then we can move on to making them both redirect to the same file.

**Comment by rs028** [comment]
Okay will try tomorrow.
I notice you took out the email alert. Can I put it back or was that the source of the problem?

**Comment by spco** [comment]
The -bea line is the one that says whether to send email alerts, and it defaults to sending the emails to your usual email address. The -M line is just to override the email address that it sends to, so it's not needed here, and makes the script less flexible. Let me know how you get on.

**Comment by rs028** [comment]
It creates a file called `base_v1.e870904` (which is empty) and one called  `atchem_error.log` (which is actually the standard output, not the standard error) in the main directory. There is also a file called `errors.output` in the `modelOutput` directory but it doesn't seem to have useful info.
Email alert works.

**Comment by spco** [comment]
My mistake - I needed a -e not a  -o on the second line. Can you try this version? That should probably then work.

The `errors.output` is a little file that I'd probably look at getting rid of from the code, it does seem to hold some odd information, not really errors. I'll raise a PR.

[AtChem_script.txt](https://github.com/AtChem/AtChem/files/1094496/AtChem_script.txt)

**Comment by rs028** [comment]
Yes it works fine. I think both files should go in the `modelOutput` directory though. 
As for `errors.output` could it be merged with `atchem_error.log`?

**Comment by spco** [comment]
I'll remove `errors.output` entirely, as it just holds some info that could go straight to standard output or error, I'll see.

If you want the standard output and standard error files to go to `modelOutput`, then you just need to change to absolute paths:

```
#PBS -o ~/git/atchem/modelOutput/atchem.log
#PBS -e ~/git/atchem/modelOutput/atchem_error.log
```
or wherever your atchem directory is. That can't be changed from inside AtChem, as AtChem just prints to stdout, and then the PBS script redirects stdout to whichever file you say.

**Comment by rs028** [comment]
Okay :+1:

**Comment by spco** [comment]
I'm now at the stage where I've run out of issues and am just tidying up some areas of the tester. Can we meet to tie up the loose ends, stamp this as version 1, and perhaps write a little bit about what might be required for the next stage of development? Would tomorrow suit?

**Comment by rs028** [comment]
I agree. Let's meet tomorrow. Please send me an invite when it suits you.

**Comment by rs028** [comment]
@spco Should the script be part of the distribution or is it specific for our system?

**Comment by spco** [comment]
I'd vote that it go into the wiki as a demo script - that way it's accessible, and users can look at it for references, but it doesn't introduce too much system-specific to the main repo.

**Comment by spco** [comment]
I'll leave you to put up a working example - perhaps in page 2, Model configuration and execution? Might be a good fit. I think it should also include the build stage and non-default arguments to point at a specific data set rather than the supplied one?

**Comment by rs028** [comment]
Yes. I was planning to go through the wiki page by page as I test the release. So far I have only done the installation pages.
It may take a bit, though, and I may ask you to review the whole thing after I am done, if that's all right.
