### ISSUE TITLE
FCVDKY output isn't used

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#169]
`FCVDKY()` is a CVODE function which returns the k-th derivative of the solution at the given time. This is called at the end of AtChem, after the final loop, but the output is never used, so it's pointless.

Is this information useful, and if so where should that output go? Or should I remove this?

**Comment by spco** [comment]
@rs028 , would this information ever be useful to a chemist?

**Comment by rs028** [comment]
Probably not. Unless it can be used as diagnostic to see if there were problems during the integration?

**Comment by spco** [comment]
That is a possibility, but I wouldn't like to comment on how useful that would be in practise, as it currently only gives a single snapshot at a single time at the end of the integration, which may not be very sensitive to problems earlier in the integration.

I don't mind leaving this code in as it is, for future possible use, or removing it for cleaner code (it's just an 8-line block to remove) - which would you like?

**Comment by rs028** [comment]
Sounds like it would be okay to remove

**Comment by spco** [comment]
Closed by #189
