### ISSUE TITLE
FCVJTIMES() is never used

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#181]
`FCVJTIMES()` calculates an approximation to `Jv`, where `J` is the system Jacobian ( `J = df/dt`) and `v` is a supplied vector. However, this is never used anywhere, in any of the solver configurations.

Some background: `FCVJTIMES()` is used when using a `FCVSPGMR` solver, if there's previously been a call to `FCVSPILSSETJAC()` with non-zero flag. Currently, this call is made if `JVapprox == 1`. However, `FCVJTIMES()` is never actually used in any of the solvers, so it's unused.

I'm leaving it there for now, but if it's unlikely to be used then it should be removed.

We need to decide whether we will use this in, say, a preconditioner.

**Comment by spco** [comment]
Note that deltaJv should probably be passed to `FCVJTIMES()` but isn't currently.

**Comment by spco** [comment]
Actually, @rs028, I think I would like to remove this function, because then I can also remove the `JVapprox` stuff that's in a couple of places, and remove this as a setting in `solver.parameters`. It's a fair bit of extra machinery lying around never to be used, but which could cause the user confusion. Does this sound ok?

**Comment by rs028** [comment]
Makes sense. 👍

**Comment by spco** [comment]
Closed by #221
