### ISSUE TITLE
Remove M from config file

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#199]
M should be calculated from Pressure and Temperature.
Remove setting in `modelConfiguration/environmentVariables.config` and calculate immediately after Pressure and Temperature are set or constrained. It should still be output as one of the environment variables (if possible).

**Comment by rs028** [comment]
ROOFOPEN should have two values only `ON` or `OFF`. Now it is `NOTUSED` or `0`, which is a bit strange.

**Comment by spco** [comment]
#227 fixes the ROOFOPEN part of this issue.
