### ISSUE TITLE
Correct handling of negative and zero angles

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#201]
When there's no light, the trig functions in the formula for the photolysis get cut off at zero. To avoid a division by 0, we currently set these to 1e-30, but it might be better to properly handle this situation instead. Worth investigating.

**Comment by rs028** [comment]
Note: the 1e-30 hack appears in other parts of the code (eg, subroutine `calcZenith`).

**Comment by spco** [comment]
Fixed by #218
