### ISSUE TITLE
JFAC species declaration

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#217]
Rather than setting `JFAC=CALC` in `environmentVariables.config` and then populating `JFacSpecies.config` with the name of the necessary photolysis rate, we should be able to remove `JFacSpecies.config`, and set e.g. `JFAC=J4` in `environmentVariables.config`. We would still then require the presence of the file `J4` in `environmentConstraints/` directory.

**Comment by spco** [comment]
@rs028 - just to check, should JFAC only be allowed to be CALC (in fact, set to the name of the relevant photolysis rate) or NOTUSED? Are we disallowing setting JFAC to a constant or to a constrained value from file?

**Comment by rs028** [comment]
No. It should be possibile to set it to a constant value or constrained.

**Comment by spco** [comment]
Right. That complicates things from what I planned. I can see that  supplying a fixed number can be done directly in `environmentVariables.config`. Which file would hold the constrained values?

**Comment by rs028** [comment]
At the moment it is a file called JFAC in the environmentConstraints folder. Or at least it was like that when we started.

**Comment by spco** [comment]
Ok.

**Comment by spco** [comment]
Closed by  #225
