### ISSUE TITLE
output of NOTUSED environmental variables

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#22]
The output of some environmental variables (eg, PRESSURE, BOUNDARYLAYERHEIGHT) when set to NOTUSED is nonsense. It should be 0 or NA

**Comment by spco** [comment]
Any of these without defaults were given default -1 in #36. Is this a sensible default, and what about the other defaults - should they be given a useful default rather than an obviously wrong default?

**Comment by rs028** [comment]
Should be okay for now. But I will look into it and post a  description of these variables in the wiki.

**Comment by rs028** [comment]
@spco I have completed the descriptions and acceptable settings list for the environmental variables. See https://github.com/AtChem/AtChem/wiki/Environment-Variables
Will check the equations and issue #23 next.

**Comment by spco** [comment]
Closed by #165
