### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#220]
Not sure this is an issue or not. Installation of openlibm goes into the main AtChem directory (following the instructions on the wiki). Should it go together with CVODE and numdiff?

**Comment by rs028** [comment]
Scratch that, the script is fine. I change this issue to "Installation problems" while I test the installation instructions.

**Comment by spco** [comment]
Ok. It's probably more an issue of changing the install instructions on the wiki to put it in the relevant place - I'll leave that to you.

**Comment by rs028** [comment]
@spco before I do any damage, I'll check with you. A new user would create a new installation by cloning the main repo rather than fork, than clone (which would be better, but that's not the point). So now this user would have origin set to the main repo.

To fix that, I think:
    git remote rename origin upstream
followed by (to setup the fork afterwards):
    git remote add origin https://github.com/user/AtChem.git

Does it make sense?

**Comment by spco** [comment]
Yes, I think that should work.
