### ISSUE TITLE
RH and H2O

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#23]
Is RH calculated correctly from H2O (and viceversa) when one is set to a constant value or constrained and the other is not?

**Comment by spco** [comment]
@rs028 , can you point me to what the correct calculation is to convert between RH and H2O?

**Comment by rs028** [comment]
@spco I will check and fix the equations of this and #14. The various options for the switches of the envVar are in the wiki (see issue #22)

**Comment by spco** [comment]
@rs028 Ok, great. I'm thinking of working on #22 shortly, to put in the correct defaults as per the wiki.

**Comment by rs028** [comment]
@spco Okay. See also #83 (it may be just a cosmetic issue, but it may be important, I am not sure) .

**Comment by rs028** [comment]
The current equation to convert RH to H2O gives correct results but underestimates H2O at high relative humidity (see plot below). This is possibily due to lack of pressure dependence.

![rh_h2o](https://cloud.githubusercontent.com/assets/7703778/25781287/dde0e3bc-332f-11e7-84e0-d7e9dd6c57ad.png)

**Comment by spco** [comment]
Can you link to the source of the current calculation, and to any more accurate formulae?

**Comment by rs028** [comment]
I have done the comparison a little bit better. I am not sure where the current implementation is taken from.
I have used the _Humidity Conversion Formulas_ document on the Vaisala website to convert the relative humidity into volume of water vapour per volume of dry air (PPM), then multiply the result by 1.0e-06*M to get the molecule cm-3.
