### ISSUE TITLE
Reorganization of configuration files

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#34]
Model configuration could be easier with less config files. In particular:

- lossRatesOutput.config and productionRatesOutput.config could be merged

- JFacSpecies.config could be merged with environmentVariables.config, eg by modifying the JFAC switch in environmentVariables.config (pending resolution of Issue #16)

- model.parameters and solver.parameters: do they need to be separate? If so are the option/switches organized logically?

**Comment by rs028** [comment]
lossRates.output and productionRates.output  do not have any output if only one species is in lossRatesOutput.config and productionRatesOutput.config

**Comment by spco** [comment]
I've opened issue #81 to address the missing output given only one species in those config files.

**Comment by spco** [comment]
@rs028 Do we want to merge lossRatesOutput.config and productionRatesOutput.config or not? Currently they are separate, so you can keep track of the production and loss of different collections of species. Is there a real benefit to merging them? That would reduce the flexibility of the code, but would simplify it a bit. I'm loathe to get rid of that separation however, as that is removing functionality - is it ok if we just ensure that the machinery is actually working?

**Comment by spco** [comment]
@rs028 Or have I misunderstood, and you're just saying the contents of the two files could be placed into the same file, but kept as separate lists of species? That would be workable.

**Comment by rs028** [comment]
@spco The second one. I think it would be easier (less error prone, maybe) to have the two lists in the same file.

**Comment by spco** [comment]
#81 seems to have fixed the missing output in lossRates.output and productionRates.output.

**Comment by spco** [comment]
Personally I'm happy to leave the lossRates.config and productionRates.config separate for now, it can always be come back to.

I'm also of the opinion that the model.parameters and solver.parameters are fine to be kept separate - there is a logical separation of the model and the solver, so reflecting that in the inputs isn't too bad. It's largely a matter of taste though.

I'll be working on the area of the JFacSpecies this afternoon, so once that is fixed, this can be closed.

**Comment by rs028** [comment]
Yeah, okay.

**Comment by rs028** [comment]
In `solver.parameters` there is this bit here:

    For one day
    96.0e+00		number of steps
    900.0e+00		step size

    for two days
    192.0e+00		number of steps
    900.0e+00		step size

    2880.0e+00	number of steps
    60.0e+00		step size

    standard
    1.0e-04		  atol
    1.0e-06	 	  rtol

It is meant to give suggestions on possibile values. I think it makes more senses to remove it and stick in the wiki. Related: I am not sure what all the parameters in this file actually mean.

**Comment by spco** [comment]
I like that suggestion - that also allows us to drop the line `-9999 End of file` : previously we had to keep that to separate the 'live' values from the reference values you've highlighted. I'm happy to raise a pull request for that, and for `model.parameters` too.

Would it be helpful to have a wiki page that both documents what the parameters mean and also gives these reference values?

**Comment by rs028** [comment]
Yes it would be very useful. You have added a lot of comments to the code (much appreciated!) but documentation is still lagging far behind.

**Comment by spco** [comment]
`model.parameters` and `solver.parameters` are tidied up by #222. The reference values have also been moved to the wiki.
