### ISSUE TITLE
mechanism.* header

### ISSUE THREAD

**Issue by rs028** [AtChem/AtChem#365]
In the `tools/mcm_example.fac` file there is this line:

    * End of Subset.  No. of Species = 30, No. of Reactions = 71 ;

The header of `mechanism.reac` and `mechanism.prod` files is:

    29 71 139 numberOfSpecies numberOfReactions numberOfGenericComplex

This probably happens with all `.fac` files. Questions:

 - either the number of species is wrong in the MCM file (there is nothing to do in this case) or they are not counted correctly by the script (if so, need to fix `mech_converter.py`) 

- what is `numberOfGenericComplex`?

**Comment by rs028** [comment]
Somewhat related: remove the header in `mechanism.ro2` (for consistency with `mechanism.species`)?

**Comment by spco** [comment]
`numberGenericComplex` is the sum of the number of reactions in Generic Rate Coefficients and Complex reactions.

I think we originally only had the header on `mechanism.prod`, and added it to `mechanism.reac` for consistnecy (or the other way around). I can't quite remember what I'm thinking of doing with these 3 files when using the function parser.

**Comment by rs028** [comment]
So it is a mistake of the MCM website? Initially I thought the reason might be the stupid Python quirk of counting things starting from zero, but I didn't have time to look into this.

As long as **we** count the correct number, then there is nothing to do here.

**Comment by spco** [comment]
I think they make the decision to count RO2 as a species, but we don't. I'd value a second opinion if you can check that you see the same behaviour. But as far as I see, we count correctly based on our choice of what is a species.
