### ISSUE TITLE
Missing output given single species of interest

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#81]
As mentioned in #34 : 

lossRates.output and productionRates.output do not have any output if only one species is in lossRatesOutput.config and productionRatesOutput.config

**Comment by spco** [comment]
@rs028 Are you able to reproduce this with the latest version? I've tried it and I seem to get the expected output.

**Comment by rs028** [comment]
@ spco Yes it works.

**Comment by spco** [comment]
Ok, I'll close this.
