### ISSUE TITLE
Remove unused variables?

### ISSUE THREAD

**Issue by spco** [AtChem/AtChem#92]
The following variables are declared, allocated, then deallocated.

culmSpeciesProduced(:), culmReactionNumber(:), culmRates(:), culmSpeciesLoss(:), culmReactionNumberLoss(:), culmRatesLoss(:)

@rs028 Can I safely remove these, since they do nothing? If there's no particular plan to use them then I would vote to remove them to declutter the code. They can always be re-added later.

**Comment by rs028** [comment]
@spco I think so. If they don't do anything and there is no indication of what they were intedend for I think it is okay to get rid of them.
